version: 0.2
phases:     
  install:
    runtime-versions:
      java: corretto17   # Ensure you have the correct Java runtime
    commands:
      - echo "Installing SonarQube Scanner..."
      - curl -o /opt/sonar-scanner-cli.zip -L "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.1.0.4477-linux-x64.zip?_gl=1*b0291u*_gcl_au*NTg2OTcxOTc0LjE3MjQ4MjM0MjM.*_ga*MTc0MTY3MTU1OS4xNzI0ODIzNDI0*_ga_9JZ0GZ5TC6*MTcyNDgyMzQyMy4xLjEuMTcyNDgzNjY4Ny4yMy4wLjA."
      - unzip /opt/sonar-scanner-cli.zip -d /opt
      - export PATH=$PATH:/opt/sonar-scanner-6.1.0.4477-linux/bin
  pre_build:
    commands:
      - echo "Running SonarQube analysis..."
      - sonar-scanner -Dsonar.projectKey=testing-project18  -Dsonar.sources=. -Dsonar.host.url=http://3.110.183.179:9000 -Dsonar.token=sqp_a556ec28282db43bd422d2cf75bb2f91dbf12c3b
  build:
    commands:
      - sam build --template-file existing-template.yaml --config-file samconfig-dev.toml
      - sam package --output-template-file package.yml  --s3-bucket api-stack-poc-testing
      - sam deploy --template-file package.yml --stack-name api-stack-poc-testing --s3-bucket api-stack-poc-testing --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND --no-confirm-changeset --no-fail-on-empty-changeset 

      - sam build --template-file new-template.yaml --config-file samconfig-dev.toml
      - sam package --output-template-file package2.yml  --s3-bucket api-stack-poc-testing2
      - sam deploy --template-file package2.yml --stack-name api-stack-poc-testing2 --s3-bucket api-stack-poc-testing2 --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND --no-confirm-changeset --no-fail-on-empty-changeset

      #- sam build --template-file latest-template.yaml --config-file samconfig-dev.toml
      #- sam package --output-template-file package3.yml  --s3-bucket api-stack-poc-testing2
      #- sam deploy --template-file package3.yml --stack-name api-stack-poc-testing3 --s3-bucket api-stack-poc-testing2 --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND --no-confirm-changeset --no-fail-on-empty-changeset

