AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  NewApiGateway:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: 'prod'
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        AddDefaultAuthorizerToCorsPreflight: False
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: arn:aws:cognito-idp:ap-south-1:010928215088:userpool/ap-south-1_YXkAOt7Bl
      Cors:
        AllowMethods: "'GET, POST, PUT, OPTIONS, DELETE, PATCH'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,User-Timezone'"
        AllowOrigin: "'*'"
        MaxAge: 86400

  NewLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs20.x
      CodeUri: ./new-lambda
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /new
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer
            RestApiId: !Ref NewApiGateway

