AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  NewApiGateway:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: 'prod'
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Sub arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/ap-south-1_YXkAOt7Bl
            IdentitySource: method.request.header.Authorization

  NewLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs20.x
      CodeUri: ./new-lambda
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /new
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer
            RestApiId: !Ref NewApiGateway

