AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'SAM Template to create a DynamoDB table for the items and names table

  '
Resources:
  testitemsDB:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: testitemsDB
    Metadata:
      SamResourceId: testitemsDB
  testStudentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: studentId
        AttributeType: S
      KeySchema:
      - AttributeName: studentId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: testStudentTable
    Metadata:
      SamResourceId: testStudentTable
  withoutexportTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: studentId
        AttributeType: S
      KeySchema:
      - AttributeName: studentId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: withoutexportTable
    Metadata:
      SamResourceId: withoutexportTable
Outputs:
  testStudentTable:
    Description: The name of the DynamoDB table for students
    Value:
      Ref: testStudentTable
    Export:
      Name: testStudentTable
  testitemsDB:
    Description: The name of the DynamoDB table
    Value:
      Ref: testitemsDB
    Export:
      Name: testitemsDB
  withoutexportTable:
    Description: The name of the DynamoDB table
    Value:
      Ref: withoutexportTable
    Export:
      Name: withoutexportTable
